# Generated by Django 3.1.1 on 2020-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter Email'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='pic_upload', verbose_name='Upload Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Enter Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Enter Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remark',
            field=models.CharField(max_length=30, verbose_name='Enter Remark'),
        ),
    ]
